# 站点信息
site_name: 小洋芋的个人博客
site_url: https://github.com/whxhcj/whxhcj.github.io/tree/my-pages
site_author: 小洋芋
site_description: 小洋芋的个人博客

# 仓库信息
repo_url: https://github.com/whxhcj/whxhcj.github.io/tree/my-pages
repo_name: personal blog
edit_uri: edit/main/docs/ # 点击编辑此页跳转的地址

theme:
  name: material
  language: zh
  favicon: images/author.jpg
  logo: images/author.jpg
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
      - navigation.instant
      - navigation.instant.progress
      - header.autohide # 滑动文章到一定深度后标题栏隐藏
      - navigation.tabs # 将 nav 的外层（页面显示在左侧）标题栏切换为标签栏（页面显示在顶部）
      - navigation.tabs.sticky # 启用标签栏粘性后，标签栏会固定在顶部（推荐和上面的一起设置）
      - navigation.tracking # 启用锚点跟踪后，地址栏中的 URL 会自动更新为内容列表中突出显示的活动锚点
      - navigation.path # 在文章顶部添加路径导航，例如：a > b > c
      - toc.follow # 当启用目录的锚点跟随时，侧边栏会自动滚动，以便活动锚点始终可见
      - navigation.top # 显示返回顶部按钮
      - search.suggest # 启用搜索建议后，搜索将显示最后一个单词最可能的补全，可以使用 → 键接受
      # - search.highlight # 当启用搜索突出显示并且用户单击搜索结果时，Material for MkDocs 将突出显示链接后出现的所有内容
      - navigation.footer # 页脚可以包含指向当前页面的上一页和下一页的链接
      - content.action.edit # 编辑跳转到 github
      - content.tooltips # 启用改进的工具提示后，Material for MkDocs 会用漂亮的小工具提示替换浏览器的 title 属性渲染逻辑。
      - content.tabs.link # 启用后，整个文档站点中的所有内容选项卡都将被链接，并在用户单击选项卡时切换到相同的标签。例如选择 C代码块后，其他代码块同步切换到 C 代码块
      - content.code.annotate
      - content.code.copy
      - content.code.select
      # - navigation.indexes # 启用后，则第一个索引页将会删除，并引用到父盒子中

  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: 切换到亮色模式

  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: light green
    toggle:
      icon: material/weather-sunny
      name: 切换到深色模式

  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: light green
    accent: teal
    toggle:
      icon: material/weather-night
      name: 切换到系统模式


    

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/whxhcj

nav:
  - 主页: index.md
  - 博客:
    - 首页: blog/index.md

plugins:
  - search # 搜索插件
  # 下方两个插件虽然比较方便，但是 gen-files 与 mkdocs-jupyter 不兼容
  # 会导致 Converting 无法工作，从而抛出 json.decoder.JSONDecodeError 异常（100% 复现）
  # 最终还是选择使用 hooks + literate-nav 的方式来嵌入配置后，再将 tab 进行自然排序
  # - gen-files:
  #     scripts:
  #       - scripts/gen_nav.py
  # 使用教程: https://oprypin.github.io/mkdocs-literate-nav/index.html
  - literate-nav: # 用SUMMARY.md生成导航
      nav_file: SUMMARY.md
  # 由于在接触 mkdocs 之前，我已经用 Jupyter 写了较多的笔记，为了减少迁移成本，启用此插件是必要的
  - mkdocs-jupyter:
      # execute: true
      # 忽略 h1 标题，采用文件名作为标题
      # ignore_h1_titles: false
      include_requirejs: true
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      # comments_path: "#__comments"
      categories:
        - categories
        - tags
  - blog:
      blog_toc: true
      # 默认情况下，该插件使帖子摘录成为可选。当帖子未定义摘录时，视图将包含整个帖子。此设置可用于使帖子摘录成为必需
      # post_excerpt: required # 必须
      post_excerpt: optional
      post_excerpt_max_authors: 2 # 设置摘录中显示的最大作者数
      archive_date_format: MMMM yyyy
      post_readtime: true # 使用此设置来控制插件是否应自动计算帖子的阅读时间，然后在帖子摘录以及帖子本身中呈现该时间


markdown_extensions:
  - toc:
      permalink: true
  # 配置教程: https://squidfunk.github.io/mkdocs-material/reference/math/#configuration
  # Arithmatex 扩展允许渲染块和内联块方程，并与 MathJax 1 （数学排版库）无缝集成。
  # 除了在 mkdocs.yml 中启用扩展之外，还需要包含 MathJax 配置和 JavaScript 运行时，这可以通过 extra_javascript 来完成
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem

  # 配置教程: https://squidfunk.github.io/mkdocs-material/reference/formatting/#configuration
  - pymdownx.mark # 高亮生效
  - pymdownx.caret # 下划线、上标生效
  - pymdownx.tilde # 删除线、下标生效
  - pymdownx.keys # 键盘样式生效
  - pymdownx.critic # 多行文本中生效上方样式，通过 {} 包裹，最终文本不会显示 {} 符号

  # 配置教程: https://squidfunk.github.io/mkdocs-material/reference/admonitions/#configuration
  # 一些支持的样式: https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - pymdownx.highlight:
      # 此选项将自动向所有代码块添加一个标题，显示正在使用的语言的名称，例如 Python 为 py
      auto_title: true
      # 此选项将为所有代码块添加行号。
      # 如果希望如果您希望向某些代码块添加行号，而不是所有代码块，请参考: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-line-numbers
      linenums: true
      # 设置此选项后，代码块的每一行都包含在 span 中，这对于行突出显示等功能正常工作至关重要
      line_spans: __span

  # 使用教程: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#highlighting-inline-code-blocks
  # InlineHilite 扩展添加了对内联代码块的语法突出显示的支持。它构建在Highlight 扩展之上，并从中获取配置
  - pymdownx.inlinehilite

  # 配置教程: https://squidfunk.github.io/mkdocs-material/reference/tooltips/#configuration
  # 此配置支持缩写，并允许构建简单的项目范围词汇表，从中心位置获取定义。
  - abbr
  - attr_list
  # Snippets 扩展可用于通过将所有缩写移动到专用文件中来实现简单的术语表
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

  # 图标/表情查询: https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
        # 配置教程： https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#configuration
        # SuperFences 扩展允许代码和内容块任意嵌套，包括警告、选项卡、列表和所有其他元素。

  - pymdownx.superfences
  # Tabbed扩展允许使用内容选项卡，这是一种将相关内容和代码块分组到可访问选项卡下的简单方法。
  - pymdownx.tabbed:
      alternate_style: true
      # 为代码块分组的标题重命名（锚点），后续可以直接通过它访问指定内容
      # 空格会被替换为 “-”
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

  # 配置教程: https://squidfunk.github.io/mkdocs-material/reference/lists/#configuration
  # 此配置允许使用定义列表和任务列表，它们都不属于标准 Markdown 语法的一部分。
  - def_list # 定义列表，使用方法：https://squidfunk.github.io/mkdocs-material/reference/lists/#using-definition-lists
  - pymdownx.tasklist:
      custom_checkbox: true

  # 配置教程: https://squidfunk.github.io/mkdocs-material/reference/grids/#configuration
  # 这种配置允许使用网格，允许将相同或不同类型的块形成矩形形状。
  - md_in_html

  - footnotes # 脚注: https://squidfunk.github.io/mkdocs-material/reference/footnotes/


extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

watch:
  - overrides
  - scripts

hooks:
  - scripts/mkdocs_hooks.py