name: publish site
on: # 在什么时候触发工作流
  push: # 在从本地master分支被push到GitHub仓库时
    branches:
      - master
  pull_request: # 在master分支合并别人提的pr时
    branches:
      - master
jobs: # 工作流的具体内容
  deploy:
    runs-on: ubuntu-latest # 创建一个新的云端虚拟机 使用最新Ubuntu系统
    steps:
      - uses: actions/checkout@v4 # 先checkout到master分支
      - uses: actions/setup-python@v5 # 再安装Python3和相关环境
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt # 使用pip包管理工具安装mkdocs-material
      - run: mkdocs gh-deploy --force # 使用mkdocs-material部署gh-pages分支